config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about", as:"about"
  resources :books,only: [:index,:show,:create,:destroy,:update,:edit]
  resources :users,only: [:index,:create,:show,:update,:edit]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user 
  
  validates :title,presence: true
  
  validates :body,presence: true,length: { maximum: 200 }
   
  
  
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books,dependent: :destroy
  has_one_attached :profile_image
  validates :name,length:{in: 2..20}
  validates :introduction, length:{ maximum: 50 }
  validates :name, uniqueness: true
  

  def get_profile_image(width,height)
   unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     profile_image.attach(io:File.open(file_path),filename: 'default-image.jpg',content_type: 'image/jpeg')
   end
   profile_image.variant(resize_to_limit: [width,height]).processed
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
   root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name ,:email])
  end
 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :correct_user, only: [:edit, :update]
  
  def new
  end

  def index
   @books = Book.all
   @book = Book.new
   @user = current_user
   @book_new = Book.new
   
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
   flash[:notice] ="You have created book successfully."
    redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user_no = current_user
      @book_new = Book.new
      @user = current_user
    render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end
  
  def edit
  @book = Book.find(params[:id])
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end 
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] ="You have updated book successfully."
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title,:body)
    
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @book_new = Book.new
  end
 
  
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @user_new = User.new
    @book_new = Book.new
    @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
     if @user == current_user
        render "edit"
     else
        redirect_to user_path(current_user.id)
     end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] ="You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
    
  end
  
  def correct_user
    @user = User.find(params[:id])
    @book = @user.books
    redirect_to(user_path(current_user.id)) unless @user == current_user
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
   
     
    
    <div class="col-md-3 ">
      
      
      
      <% if flash[:notice] %>
      <% end %>
      
      
      
      
      
      <h2>User info</h2>
      
      
      
      
 
      
      
       <%= image_tag user.get_profile_image(100,100) %>
       
      <tbody>
        <div class="row ml-2 pt-3 pb-3 border-top font-weight-bold">
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          </div>
          <div class="row ml-2 mb-3 pt-3 pb-3 border-top font-weight-bold">
          <th>introduction</th>
          <th><%= user.introduction %></th>
          </div>
        </tr>
      </tbody>
      </table>
      
      
      
        
 
       
      
      
      
      <div class="  mt-3 mb-4 col-12" >
          
          <%= link_to edit_user_path(user.id) do %>
       <span class="btn btn-outline-secondary w-100"><i class="fas fa-user-cog "></i></span>
        <% end %>
        
        
      </div>
      <h2 class="font-weight-20">New book</h2>
      
      
      
      <% if @book.errors.any? %>
 <div id="error">
   <div class="errors-text">
  <%= @book.errors.count %>errors prohibited this book from being saved:
  </div>
 <ul>
   <% @book.errors.full_messages.each do |message| %>
   <li class="error-message"><%= message %></li>
   <% end %>
 </ul>
 </div>
 
 <% end %>
      
      
      
      
      <%= form_with model:nbook,url:'/books',method: :post do |f| %>
      
      <div class="field mt-2">
        <label class="book_title">Title</label>
        <%= f.text_field:title ,class:"form-control" %>
      </div>
      
      <div class="field mt-2">
        <label>Opinion</label>
        <%= f.text_area:body ,class:"form-control" %>
      </div>
      <div class="actions mt-3">
        <%= f.submit 'Create Book',class:"btn btn-success"%>
     <% end %>
      </div>
    </div>
 

app/views/books/edit.html.erb
<div class="container">
<div class="row  justify-content-center">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0  mx-auto  d-inline-block pt-3 ">
    
    
    
<h1 class="">Editing Book</h1>


　　<% if @book.errors.any? %>
      <div id="error">
       <div class="errors-text">
       <h3><%= @book.errors.count %> errors prohibited obj from being saved</h3>
     </div>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
   <li class="error-message"><%= message %></li>
       <% end %>
    </ul>
    </div>
      <% end %>



<%= form_with model:@book do |f| %>
<label for="inputBook"><span class="text-left">Title</span></label><br>
<%= f.text_field :title,autofocus: true,id:"inputBook",class:"form-control" %><br>
<label>Opinion</label><br>
<%= f.text_area :body,autofocus: true,id:"inputBook" ,class:"form-control" %> <br>


<%=f.submit "Update Book",class:"btn btn-success mb-3" %>

<% end %>

<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back",books_path %>

  </div>
 </div>
</div>

app/views/books/index.html.erb
<div class="container mt-3">
  <div class="row">
      
      
      
      
    <%= render 'list',book: @book ,nbook: @book_new, user: @user %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      
     
      
      
      
      <table class="border-top  border-bottom w-100 ">
        <thead class=" font-weight-bold">
          <tr>
           <th></th>
           <th class="pt-3 pb-3 pr-5">Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
         </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody class="border-top border-bottom btn-outline-light">
          <td><%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
           </td>
          <td><%= link_to book.title,book_path(book.id) %></td>
          <td class=text-dark><%= book.body %></td>
        </tbody>
        <% end %>
      </table>
      
    </div>
    </div> 
 </div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container mt-3">
  <div class="row">
      
   <%= render 'list', nbook: @book_new, book: @book, user: @user %>
   
   
   <div class="col-md-8 offset-md-1">
     <h2>Book detail</h2>
     <table class="w-100">
       <thead>
         <tr>
           <th></th>
           <th></th>
           <th></th>
           <th colspan="3"></th>
         </tr>
       </thead>
       
       <tbody class="border-top">
           
         <td><%= link_to user_path(@user.id) do %>
          <%= image_tag @user.get_profile_image(100,100) %>
          <span class="d-block"><%= @user.name  %></span>
          <% end %></td>
         
         <td class="w-50 pl-5"><%= link_to book_path(@book.id) do %>
          <%= @book.title %>
          <% end %></td>
         <td class="w-50  "><%= @book.body %></td>
         <% if @book.user == current_user %>
         <td><%= link_to "Edit",edit_book_path(@book.id) ,class:"btn btn-success btn-sm" %></td>
         <td><%= link_to "Destroy",book_path(@book),method: :delete,"data-confirm" => "本当に消しますか？" ,class:"btn btn-danger btn-sm"%></td>
       </tbody>
         <% end %>
         
     </table>
   </div>
     
  </div>
</div>

app/views/homes/about.html.erb
<h1 class="text-center mt-3">Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>

app/views/homes/top.html.erb
<div class="container">

 <div class="mx-auto ">
   <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6 mt-3">
   <h1>welcome to<i class="fas fa-book"><strong></i> Bookers</strong>!!</h1>

<p>In <i class="fas fa-book"></i><string class="font-weight-bold">Bookers,</string></p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>

   <div class="row  justify-content-center ">
   <div class="center-block  mb-3 w-100 text-center ">
    <%= link_to "Log in",new_user_session_path,class:"text-white   btn btn-info col-10 btn-sm" %>
     </div>
     </div>
     <div class=" row justify-content-center">
     <div class="center-block  mb-3 w-100 text-center ">
      <%= link_to "Sign up", new_user_registration_path ,class:"text-white  btn btn-success col-10 btn-sm" %>
       <span></span>
      
       </div>
     </div>
   </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   <script src="https://kit.fontawesome.com/936e751774.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class=container>
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                       aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item" >
         <%= link_to user_path(current_user.id), class:"nav-link text-white" do %>
         <i class="fas fa-home" ></i> Home
        <% end %>
        </li>
      <li class="nav-item">
        <%= link_to users_path, class:"nav-link text-white" do %>
        <i class="fas fa-users"></i> Users
        <% end %>
        </li>
      <li class="nav-item">
        <%= link_to books_path, class:"nav-link text-white" do %>
        <i class="fas fa-book-open"></i> Books
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to destroy_user_session_path,method: :delete, class:"nav-link text-white" do %>
        <i class="fas fa-sign-out-alt"></i> Log out
        <% end %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to root_path, class:"nav-link text-white" do %>
        <i class="fas fa-home"></i> Home
        <% end %>
      </li>
      <li class="nav-item">
       <%= link_to '/home/about',class:"nav-link text-white" do %>
       <i class="fas fa-link" ></i> About
       <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_registration_path, class:"nav-link text-white" do %>
        <i class="fas fa-user-plus"></i> Sign up
        <% end %>
      </li>
      <li class="nav-item">
      <%= link_to new_user_session_path, class:"nav-link text-white" do %>
      <i class="fas fa-sign-in-alt"></i> Log in
      <% end %>
      </li>
      <% end %>
      </ul>
      </div>
      </div>
    </nav>
    </header>
    
    
    
    
    <main>
     <% flash.each do |key,value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  
  
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
      <p class="mx-auto">CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0  mx-auto   pt-3">
      <h2>User info</h2>
      
      <% if @user.errors.any? %>
      <div id="error">
       <div class="errors-text">
       <h3><%= @user.errors.count %> errors prohibited obj from being saved</h3>
     </div>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
   <li class="error-message"><%= message %></li>
       <% end %>
    </ul>
    </div>
      <% end %>
      
      
      
      
      <%= form_with model:@user do |f| %> 
      <label for="inputUser">Name</label><br>
      <%= f.text_field :name,autofocus:true,id:"inputUser",class:"form-control" %><br>
      <label for="inputUser">Image</label><br>
      <%= f.file_field :profile_image,placeholder:"プロフィール画像",accept:"image/*" ,class:"mb-3"%><br>
      <label for="inputUser"><span class="mt-5">Introduction</span></label><br>
      <%= f.text_area :introduction, autofocus:true, id:"inputUser" ,class:"form-control" %><br>
      <%= f.submit "Update User" ,class:"btn btn-secondary" %><br>
       <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-3">
  <div class="row">
    <%= render 'books/list',book: @book,nbook: @book_new,user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="w-100 mt-2 border-top">
        <thead>
        <tr class=" border-top border-bottom font-weight-bold">
          <th class=" pt-3 pb-3 ,ml-5 pl-3">image</th>
          <th class="pt-3 pb-3 pr-5">name</th>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
      <tbody class="border-top pb-2">
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td><%= user.name %></td>
        <td class="align-items-start"><%= link_to "Show",user_path(user.id) %></td>
      </tbody>
      <% end %>
      </table>
      
      
      
      
      
      
    </div>
    
    
  </div>
</div>

app/views/users/show.html.erb
<div class="container pt-3">
  <div class="row">
    <%= render 'books/list', book: @book,nbook: @book_new, user: @user %>
    
    
    <div class="col-md-8 offset-md-1">
      <h2 class="border-bottom pb-2">Books</h2>
     <table class="w-100 ">
       <thead>
         <tr>
           <th></th>
           <th class="pb-2">Title</th>
           <th class="pb-2">Opinion</th>
           <th colspan="3"></th>
         </tr>
       </thead>
       <% @books.each do |book| %>
       <tbody class="border-top btn-outline-light">
           
         <td class=" pt-2 pb-2">
             <%= link_to user_path(@user.id) do %>
          <%= image_tag @user.get_profile_image(80,80)%></td>
         <% end %>
         <td><%= link_to book_path(book.id) do %>
           <%= book.title %></td>
           <% end %>
         <td class="text-dark"><%= book.body %></td>
         
       </tbody>
        <% end %>
         
     </table>
    </div>
  </div>
</div>